services:
    market_web:
        container_name: market_web
        image: nginx:alpine
        ports:
            - "8060:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - market_app
        networks:
            - market_network
    market_app:
        container_name: market_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - market_db
        volumes:
            - ./:/var/www
        networks:
            - market_network
        ports:
            - "9080:9000"
    market_db:
        image: mysql
        container_name: market_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - market_database:/var/lib/mysql
        networks:
            - market_network
        ports:
            -   "3207:3206"
    market_redis:
        container_name: market_redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6388:6380"
        networks:
            - market_network
    node:
        image: node:22
        container_name: chat_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5173:5173"  # For Vite development server
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm run build"
        networks:
            - market_network
networks:
    market_network:
        driver: bridge
volumes:
    market_database:

        
